---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pllucian-playground
  namespace: dev
  labels:
    app: pllucian-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pllucian-playground
  template:
    metadata:
      labels:
        app: pllucian-playground
    spec:
      containers:
      - name: pllucian-playground
        image: pllucian/playground:v2
        ports:
        - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: pllucian-playground
  namespace: dev
  labels:
    app: pllucian-playground
spec:
  selector:
    app: pllucian-playground
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
  type: LoadBalancer
